## Make relevant library imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection
## Load in data from the relevant directory and inspect the dataframe.
## inspect NaNs, datatypes, and summary statistics

## UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 80684: invalid start byte

In [17]:
df = pd.read_csv("AviationData.csv", encoding="cp1252")
df.head()

C:\Users\Admin\AppData\Local\Temp\ipykernel_22076\1613337455.py:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("AviationData.csv", encoding="cp1252")

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980

In [9]:

df.shape

(88889, 31)

In [10]:

df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [11]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50132 non-null  object
 9   Airport.Name            52704 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87507 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81793 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82505 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [12]:

df.isnull().sum()

Event.Id                      0
Investigation.Type            0
Accident.Number               0
Event.Date                    0
Location                     52
Country                     226
Latitude                  54507
Longitude                 54516
Airport.Code              38757
Airport.Name              36185
Injury.Severity            1000
Aircraft.damage            3194
Aircraft.Category         56602
Registration.Number        1382
Make                         63
Model                        92
Amateur.Built               102
Number.of.Engines          6084
Engine.Type                7096
FAR.Description           56866
Schedule                  76307
Purpose.of.flight          6192
Air.carrier               72241
Total.Fatal.Injuries      11401
Total.Serious.Injuries    12510
Total.Minor.Injuries      11933
Total.Uninjured            5912
Weather.Condition          4492
Broad.phase.of.flight     27165
Report.Status              6384
Publication.Date          13771
dtype: int64

In [13]:

df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [14]:

df.duplicated().sum()

0

## Data Cleaning

In [19]:

print(df["Aircraft.Category"].value_counts(dropna=False))


print(df["Amateur.Built"].value_counts(dropna=False))


print(df["Event.Date"].head())

Aircraft.Category
NaN                  56602
Airplane             27617
Helicopter            3440
Glider                 508
Balloon                231
Gyrocraft              173
Weight-Shift           161
Powered Parachute       91
Ultralight              30
Unknown                 14
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
ULTR                     1
Name: count, dtype: int64
Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64
0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: object

In [20]:

df[["Aircraft.Category", "Amateur.Built", "Event.Date"]].isnull().sum()

Aircraft.Category    56602
Amateur.Built          102
Event.Date               0
dtype: int64

In [21]:

df = df[df["Aircraft.Category"] == "Airplane"].copy()

df["Aircraft.Category"].value_counts(dropna=False)

Aircraft.Category
Airplane    27617
Name: count, dtype: int64

In [22]:

df = df[df["Amateur.Built"] == "No"].copy()

df["Amateur.Built"].value_counts(dropna=False)

Amateur.Built
No    24417
Name: count, dtype: int64

In [23]:

df["Event.Date"] = pd.to_datetime(
    df["Event.Date"],
    errors="coerce"
)

df["Event.Date"].dtype

dtype('<M8[ns]')

In [24]:

df = df.dropna(subset=["Event.Date"]).copy()

In [25]:

start_date = pd.Timestamp("1983-01-01")
end_date = pd.Timestamp("2023-12-31")

df = df[
    (df["Event.Date"] >= start_date) &
    (df["Event.Date"] <= end_date)
].copy()

## Cleaning and Constructing Key Measurables

In [31]:


df = df.rename(columns={"Aircraft.damage": "Aircraft.Damage"})

# column name
print("Aircraft.Damage" in df.columns)

True

In [53]:
print(df_clean.shape)
print(df_clean.columns.tolist())

(17879, 0)
[]

In [ ]:

injury_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured",
    "Aircraft.Damage"
]

# Inspect data
print(df[injury_columns].head())

# Check data types and missing values
print(df[injury_columns].info())
print(df[injury_columns].isnull().sum())

# Inspect damage categories
print(df["Aircraft.Damage"].value_counts(dropna=False))

      Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  \
4149                   NaN                     NaN                   NaN
4150                   NaN                     NaN                   NaN
4171                   1.0                     1.0                   NaN
4285                   1.0                     NaN                   NaN
5957                   NaN                     NaN                   NaN

      Total.Uninjured Aircraft.Damage
4149            588.0           Minor
4150            588.0           Minor
4171              NaN       Destroyed
4285              4.0             NaN
5957            289.0           Minor
<class 'pandas.core.frame.DataFrame'>
Index: 21447 entries, 4149 to 88886
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Total.Fatal.Injuries    18697 non-null  float64
 1   Total.Serious.Injuries  18619 non-null  float64
 2   Total.Minor.Injuries    18903 non-null  float64
 3   Total.Uninjured         20736 non-null  float64
 4   Aircraft.Damage         20220 non-null  object
dtypes: float64(4), object(1)
memory usage: 1005.3+ KB
None
Total.Fatal.Injuries      2750
Total.Serious.Injuries    2828
Total.Minor.Injuries      2544
Total.Uninjured            711
Aircraft.Damage           1227
dtype: int64
Aircraft.Damage
Substantial    16990
Destroyed       2316
NaN             1227
Minor            817
Unknown           97
Name: count, dtype: int64

In [34]:
# List the injury columns
injury_columns = [
    "Total.Fatal.Injuries",
    "Total.Serious.Injuries",
    "Total.Minor.Injuries",
    "Total.Uninjured"
]

# Convert the injury columns to numbers
for col in injury_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Calculate the estimated total number of occupants
df["Total.Occupants"] = df[injury_columns].sum(
    axis=1,
    min_count=4
)

# Check that the new column exists
print(df[["Total.Occupants"]].head())

      Total.Occupants
4149              NaN
4150              NaN
4171              NaN
4285              NaN
5957              NaN

In [35]:

# Combine fatal and serious injury counts.


df["Fatal.Serious.Injuries"] = df[
    ["Total.Fatal.Injuries", "Total.Serious.Injuries"]
].sum(axis=1, min_count=2)

# Calculate the proportion of occupants with fatal or serious injuries.


df["Fatal.Serious.Injury.Rate"] = (
    df["Fatal.Serious.Injuries"] / df["Total.Occupants"]
).where(df["Total.Occupants"] > 0)


df[
    [
        "Total.Occupants",
        "Fatal.Serious.Injuries",
        "Fatal.Serious.Injury.Rate"
    ]
].head(10)

      Total.Occupants  Fatal.Serious.Injuries  Fatal.Serious.Injury.Rate
4149              NaN                     NaN                        NaN
4150              NaN                     NaN                        NaN
4171              NaN                     2.0                        NaN
4285              NaN                     NaN                        NaN
5957              NaN                     NaN                        NaN
5960              NaN                    13.0                        NaN
6669              NaN                     NaN                        NaN
6760              NaN                     NaN                        NaN
6806              NaN                     NaN                        NaN
7084              NaN                     NaN                        NaN

In [37]:

# Missing values remain missing.

df["Aircraft.Damage"] = (
    df["Aircraft.Damage"]
    .astype("string")
    .str.strip()
    .str.title()
)

# Check the cleaned categories
print(df["Aircraft.Damage"].value_counts(dropna=False))

Aircraft.Damage
Substantial    16990
Destroyed       2316
<NA>            1227
Minor            817
Unknown           97
Name: count, dtype: Int64

In [ ]:

# Recognize the damage categories 


known_damage = ["Destroyed", "Substantial", "Minor"]



df["Aircraft.Destroyed"] = np.nan

# Record confirmed destruction
df.loc[
    df["Aircraft.Damage"] == "Destroyed",
    "Aircraft.Destroyed"
] = 1


df.loc[
    df["Aircraft.Damage"].isin(["Substantial", "Minor"]),
    "Aircraft.Destroyed"
] = 0


print(df["Aircraft.Destroyed"].value_counts(dropna=False))

Aircraft.Destroyed
0.0    17807
1.0     2316
NaN     1324
Name: count, dtype: int64

## Investigate the Make column

In [41]:

print("Missing Make values:", df["Make"].isna().sum())

print("Unique Makes before cleaning:", df["Make"].nunique())


print(df["Make"].value_counts(dropna=False).head(20))

Missing Make values: 3
Unique Makes before cleaning: 1332
Make
CESSNA                4867
PIPER                 2803
Cessna                2279
Piper                 1186
BOEING                1037
BEECH                 1018
Beech                  413
MOONEY                 238
Boeing                 227
CIRRUS DESIGN CORP     218
AIR TRACTOR INC        217
AIRBUS                 215
BELLANCA               158
AERONCA                149
MAULE                  144
Mooney                 125
EMBRAER                123
Air Tractor            117
LUSCOMBE                95
CHAMPION                91
Name: count, dtype: int64

In [42]:


print("Missing Make values:", df["Make"].isna().sum())


print("Unique Makes before cleaning:", df["Make"].nunique())


print(df["Make"].value_counts(dropna=False).head(20))

Missing Make values: 3
Unique Makes before cleaning: 1332
Make
CESSNA                4867
PIPER                 2803
Cessna                2279
Piper                 1186
BOEING                1037
BEECH                 1018
Beech                  413
MOONEY                 238
Boeing                 227
CIRRUS DESIGN CORP     218
AIR TRACTOR INC        217
AIRBUS                 215
BELLANCA               158
AERONCA                149
MAULE                  144
Mooney                 125
EMBRAER                123
Air Tractor            117
LUSCOMBE                95
CHAMPION                91
Name: count, dtype: int64

In [43]:


df_clean = df.copy()


df_clean["Make"] = (
    df_clean["Make"]
    .astype("string")
    .str.strip()
    .str.upper()
)


df_clean["Make"] = df_clean["Make"].replace("", pd.NA)


df_clean = df_clean.dropna(subset=["Make"]).copy()


make_counts = df_clean["Make"].value_counts()


valid_makes = make_counts[make_counts >= 50].index

df_clean = df_clean[
    df_clean["Make"].isin(valid_makes)
].copy()

print("Rows remaining:", len(df_clean))
print("Manufacturers remaining:", df_clean["Make"].nunique())
print("\nTop 20 manufacturers:")
print(df_clean["Make"].value_counts().head(20))

Rows remaining: 17892
Manufacturers remaining: 36

Top 20 manufacturers:
Make
CESSNA                7146
PIPER                 3989
BEECH                 1431
BOEING                1264
MOONEY                 363
AIRBUS                 243
CIRRUS DESIGN CORP     220
BELLANCA               219
AIR TRACTOR INC        219
MAULE                  215
AIR TRACTOR            206
AERONCA                200
CHAMPION               158
EMBRAER                153
GRUMMAN                147
LUSCOMBE               141
CIRRUS                 137
STINSON                129
MCDONNELL DOUGLAS      108
NORTH AMERICAN         106
Name: count, dtype: Int64

## Inspect Model column

In [44]:

df_clean = df_clean.dropna(subset=["Model"]).copy()

df_clean["Model"] = df_clean["Model"].astype(str).str.strip()
df_clean = df_clean[df_clean["Model"] != ""]

print(df_clean["Model"].isna().sum())

0

In [45]:

print(df_clean.groupby(["Make", "Model"]).size().sort_values(ascending=False).head(20))

Make                Model
CESSNA              172          769
BOEING              737          403
CESSNA              152          316
                    182          304
                    172S         276
PIPER               PA28         273
CESSNA              172N         249
                    180          213
                    172M         180
                    150          179
PIPER               PA-18-150    175
                    PA-28-140    169
BEECH               A36          164
CIRRUS DESIGN CORP  SR22         144
CESSNA              172P         143
                    140          116
                    172R         109
                    170B         107
PIPER               PA-28-180    105
                    PA-28-161    102
dtype: int64

In [46]:

df_clean["Aircraft.Type"] = df_clean["Make"] + " | " + df_clean["Model"]

print(df_clean[["Make", "Model", "Aircraft.Type"]].head())

              Make      Model         Aircraft.Type
4150        BOEING        747          BOEING | 747
4171         PIPER  PA-28-140     PIPER | PA-28-140
4285  DE HAVILLAND      DHC-6  DE HAVILLAND | DHC-6
6760        BOEING    727-200      BOEING | 727-200
6806         BEECH        C35           BEECH | C35

## Cleaning other columns

In [47]:

columns = [
    "Engine.Type",
    "Weather.Condition",
    "Number.of.Engines",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

for col in columns:
    print("\n", col)
    print(df_clean[col].value_counts(dropna=False).head(15))

 Engine.Type
Engine.Type
Reciprocating      12835
NaN                 3214
Turbo Prop           931
Turbo Fan            701
Unknown              105
Turbo Jet             71
Geared Turbofan       12
Turbo Shaft            9
UNK                    1
Name: count, dtype: int64

 Weather.Condition
Weather.Condition
VMC    14295
NaN     2417
IMC      905
Unk      186
UNK       76
Name: count, dtype: int64

 Number.of.Engines
Number.of.Engines
1.0    13222
2.0     2470
NaN     2089
4.0       67
3.0       26
0.0        5
Name: count, dtype: int64

 Purpose.of.flight
Purpose.of.flight
Personal               9844
NaN                    3047
Instructional          2410
Aerial Application      724
Business                409
Unknown                 303
Positioning             269
Skydiving               157
Aerial Observation      147
Other Work Use          121
Banner Tow               86
Flight Test              73
Ferry                    72
Executive/corporate      65
Glider Tow               29
Name: count, dtype: int64

 Broad.phase.of.flight
Broad.phase.of.flight
NaN            15427
Landing         1110
Takeoff          425
Cruise           238
Approach         210
Maneuvering      127
Taxi              99
Go-around         81
Descent           62
Climb             52
Standing          35
Unknown           11
Other              2
Name: count, dtype: int64

In [48]:

text_columns = [
    "Engine.Type",
    "Weather.Condition",
    "Purpose.of.flight",
    "Broad.phase.of.flight"
]

for col in text_columns:
    df_clean[col] = (
        df_clean[col]
        .astype("string")
        .str.strip()
        .str.upper()
    )

    
    df_clean[col] = df_clean[col].replace(
        ["", "UNKNOWN", "UNK", "N/A", "NONE", "NAN"],
        pd.NA
    )


df_clean["Number.of.Engines"] = pd.to_numeric(
    df_clean["Number.of.Engines"],
    errors="coerce"
)


invalid_engines = (
    (df_clean["Number.of.Engines"] <= 0) |
    (df_clean["Number.of.Engines"] % 1 != 0)
)

df_clean.loc[invalid_engines, "Number.of.Engines"] = pd.NA

print("Cleaning complete!")

Cleaning complete!

In [49]:

for col in columns:
    print("\n", col)
    print(df_clean[col].value_counts(dropna=False).head(10))

 Engine.Type
Engine.Type
RECIPROCATING      12835
<NA>                3320
TURBO PROP           931
TURBO FAN            701
TURBO JET             71
GEARED TURBOFAN       12
TURBO SHAFT            9
Name: count, dtype: Int64

 Weather.Condition
Weather.Condition
VMC     14295
<NA>     2679
IMC       905
Name: count, dtype: Int64

 Number.of.Engines
Number.of.Engines
1.0    13222
2.0     2470
NaN     2094
4.0       67
3.0       26
Name: count, dtype: int64

 Purpose.of.flight
Purpose.of.flight
PERSONAL              9844
<NA>                  3350
INSTRUCTIONAL         2410
AERIAL APPLICATION     724
BUSINESS               409
POSITIONING            269
SKYDIVING              157
AERIAL OBSERVATION     147
OTHER WORK USE         121
BANNER TOW              86
Name: count, dtype: Int64

 Broad.phase.of.flight
Broad.phase.of.flight
<NA>           15438
LANDING         1110
TAKEOFF          425
CRUISE           238
APPROACH         210
MANEUVERING      127
TAXI              99
GO-AROUND         81
DESCENT           62
CLIMB             52
Name: count, dtype: Int64

## Column Removal

In [50]:


print(df_clean.notna().sum())


df_clean = df_clean.dropna(axis=1, thresh=20001)


print("Remaining columns:")
print(df_clean.columns.tolist())

Event.Id                     17879
Investigation.Type           17879
Accident.Number              17879
Event.Date                   17879
Location                     17875
Country                      17878
Latitude                     15981
Longitude                    15978
Airport.Code                 11648
Airport.Name                 11754
Injury.Severity              17162
Aircraft.Damage              16815
Aircraft.Category            17879
Registration.Number          17715
Make                         17879
Model                        17879
Amateur.Built                17879
Number.of.Engines            15785
Engine.Type                  14559
FAR.Description              17535
Schedule                      2139
Purpose.of.flight            14529
Air.carrier                   8448
Total.Fatal.Injuries         15493
Total.Serious.Injuries       15421
Total.Minor.Injuries         15656
Total.Uninjured              17292
Weather.Condition            15200
Broad.phase.of.flight         2441
Report.Status                14094
Publication.Date             17091
Fatal.Serious.Injuries       15297
Total.Occupants              15259
Fatal.Serious.Injury.Rate    14519
Aircraft.Destroyed           16733
Aircraft.Type                17879
dtype: int64
Remaining columns:
[]

## Save DataFrame to csv

In [51]:

# Save the cleaned DataFrame to a CSV file
df_clean.to_csv("cleaned_aviation_data.csv", index=False)

print("Cleaned data saved successfully!")

Cleaned data saved successfully!

In [54]:
df_clean.to_csv("cleaned_aviation_data.csv", index=False)

In [57]:
df_clean = df.loc[:, df.notna().mean() > 0.2]

In [58]:
print(df_clean.shape)    
df_clean.to_csv("cleaned_aviation_data.csv", index=False)

df = pd.read_csv("cleaned_aviation_data.csv")
df.head()

(21447, 33)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,Fatal.Serious.Injuries,Total.Occupants,Fatal.Serious.Injury.Rate,Aircraft.Destroyed
0,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Probable Cause,04-12-2014,NaN,NaN,NaN,0.0
1,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Probable Cause,04-12-2014,NaN,NaN,NaN,0.0
2,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,IMC,Probable Cause,02-05-2011,2.0,NaN,NaN,1.0
3,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,NaN,4.0,VMC,Probable Cause,17-10-2016,NaN,NaN,NaN,NaN
4,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,289.0,VMC,Probable Cause,01-02-2016,NaN,NaN,NaN,0.0

In [60]:
import pandas as pd

df = pd.read_csv("cleaned_aviation_data.csv")
print(df.shape)
df.head()

(21447, 33)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Report.Status,Publication.Date,Fatal.Serious.Injuries,Total.Occupants,Fatal.Serious.Injury.Rate,Aircraft.Destroyed
0,20001214X42478,Incident,LAX83IA149B,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Probable Cause,04-12-2014,NaN,NaN,NaN,0.0
1,20001214X42478,Incident,LAX83IA149A,1983-03-18,"LOS ANGELES, CA",United States,NaN,NaN,LAX,LOS ANGELES INTL,...,NaN,NaN,588.0,VMC,Probable Cause,04-12-2014,NaN,NaN,NaN,0.0
2,20001214X42331,Accident,ATL83FA140,1983-03-20,"CROSSVILLE, TN",United States,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,IMC,Probable Cause,02-05-2011,2.0,NaN,NaN,1.0
3,20001214X42672,Accident,FTW83LA177,1983-04-02,"MCKINNEY, TX",United States,NaN,NaN,TX05,AERO COUNTRY,...,NaN,NaN,4.0,VMC,Probable Cause,17-10-2016,NaN,NaN,NaN,NaN
4,20001214X44248,Incident,MIA83IA210,1983-08-21,"NORFOLK, VA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,289.0,VMC,Probable Cause,01-02-2016,NaN,NaN,NaN,0.0